New changes
pascalmolin/hcperiods pull request #7
Opened 2016-12-16 17:27 UTC by christianneurohr

See git commit comments for details.

2016-12-16 19:49 UTC, pascalmolin commented
Several general things first:
- now your changes are automatically tested, here you can see things fail
- do not keep your Makefile, I updated the main to handle all cases (me, you, travis)
- as you can see, I have put the relevant information for computing shifts in the edge_t, so that rho does not need to be computed

2016-12-16 19:52 UTC, pascalmolin commented
Now concerning nth_root_turn : you can simplify. There is no need to multiply by -1 each time, just accumulate in an int and change sign at the end. And the signs can just be ints, not arb types.
Also you can remove blank lines at the end.

2016-12-16 19:54 UTC, pascalmolin requested changes
no tmp files! (here main.toc)

2016-12-16 20:20 UTC, pascalmolin commented on arb/intersections_tree.c
> +            else if (ek.a == el.b)
this case does not occur

2016-12-16 20:22 UTC, pascalmolin commented on arb/intersections_tree.c
>                  /* no intersection */
nice catch

2016-12-16 20:55 UTC, christianneurohr commented
Thanks for the comments and updates. It were my first steps with arb, I
think it will be better soon!

2016-12-16 21:22 GMT+01:00 pascalmolin <notifications@github.com>:

> *@pascalmolin* commented on this pull request.
> ------------------------------
>
> In arb/intersections_tree.c
> <https://github.com/pascalmolin/hcperiods/pull/7#pullrequestreview-13404657>
> :
>
> >          for (l = k + 1; l < d - 1; l++)
>          {
>              edge_t el = tree->e[l];
>
> -            if (el.a != ek.a && el.a != ek.b)
> +            if (ek.a != el.a && ek.b != el.a)
>                  /* no intersection */
>
> nice catch
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pascalmolin/hcperiods/pull/7#pullrequestreview-13404657>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFqZFpdBy-ei7gpEq41YpGDrIvX8rK_eks5rIvL9gaJpZM4LPajh>
> .
>

2016-12-16 21:27 UTC, pascalmolin commented
No problem. I will push the intersection tree file in a few minutes, I
included your changes and I will add a test file.
As you may have guessed from the code, I rewrote your theorem 5.1 in a more
compact way.

Then I think it will be easier to close the pull request so that you start
a new one with only a 2nd version of the nth_root.

An easy way to get started would also be to contribute tests, you see how
they are written. Some could check the output is the same as the one you
got from magma.
Do not hesitate to use branches to avoid messing up everything when a
commit is finally not taken.

Pascal

2016-12-16 21:55 GMT+01:00 christianneurohr <notifications@github.com>:

> Thanks for the comments and updates. It were my first steps with arb, I
> think it will be better soon!
>
> 2016-12-16 21:22 GMT+01:00 pascalmolin <notifications@github.com>:
>
> > *@pascalmolin* commented on this pull request.
> > ------------------------------
> >
> > In arb/intersections_tree.c
> > <https://github.com/pascalmolin/hcperiods/pull/7#
> pullrequestreview-13404657>
> > :
> >
> > > for (l = k + 1; l < d - 1; l++)
> > {
> > edge_t el = tree->e[l];
> >
> > - if (el.a != ek.a && el.a != ek.b)
> > + if (ek.a != el.a && ek.b != el.a)
> > /* no intersection */
> >
> > nice catch
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/pascalmolin/hcperiods/pull/7#
> pullrequestreview-13404657>,
> > or mute the thread
> > <https://github.com/notifications/unsubscribe-auth/AFqZFpdBy-
> ei7gpEq41YpGDrIvX8rK_eks5rIvL9gaJpZM4LPajh>
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pascalmolin/hcperiods/pull/7#issuecomment-267693710>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADL0jfgtVEnS8897qZIqFIXY7544aa7Qks5rIvqwgaJpZM4LPajh>
> .
>

2016-12-19 09:52 UTC, christianneurohr commented
Hello Pascal,

i pushed the reworked nth_root. I like your simplification of Thm 5.1., you
think it should be like that in the paper as well?
Also, your Makefile isn't working for me (cannot 'make' as it doesnt find
arb.h) and I don't know how to run the test files, any idea how to fix that?

Christian

2016-12-16 22:27 GMT+01:00 pascalmolin <notifications@github.com>:

> No problem. I will push the intersection tree file in a few minutes, I
> included your changes and I will add a test file.
> As you may have guessed from the code, I rewrote your theorem 5.1 in a more
> compact way.
>
> Then I think it will be easier to close the pull request so that you start
> a new one with only a 2nd version of the nth_root.
>
> An easy way to get started would also be to contribute tests, you see how
> they are written. Some could check the output is the same as the one you
> got from magma.
> Do not hesitate to use branches to avoid messing up everything when a
> commit is finally not taken.
>
> Pascal
>
> 2016-12-16 21:55 GMT+01:00 christianneurohr <notifications@github.com>:
>
> > Thanks for the comments and updates. It were my first steps with arb, I
> > think it will be better soon!
> >
> > 2016-12-16 21:22 GMT+01:00 pascalmolin <notifications@github.com>:
> >
> > > *@pascalmolin* commented on this pull request.
> > > ------------------------------
> > >
> > > In arb/intersections_tree.c
> > > <https://github.com/pascalmolin/hcperiods/pull/7#
> > pullrequestreview-13404657>
> > > :
> > >
> > > > for (l = k + 1; l < d - 1; l++)
> > > {
> > > edge_t el = tree->e[l];
> > >
> > > - if (el.a != ek.a && el.a != ek.b)
> > > + if (ek.a != el.a && ek.b != el.a)
> > > /* no intersection */
> > >
> > > nice catch
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/pascalmolin/hcperiods/pull/7#
> > pullrequestreview-13404657>,
> > > or mute the thread
> > > <https://github.com/notifications/unsubscribe-auth/AFqZFpdBy-
> > ei7gpEq41YpGDrIvX8rK_eks5rIvL9gaJpZM4LPajh>
> > > .
> > >
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/pascalmolin/hcperiods/pull/7#issuecomment-267693710
> >,
> > or mute the thread
> > <https://github.com/notifications/unsubscribe-auth/
> ADL0jfgtVEnS8897qZIqFIXY7544aa7Qks5rIvqwgaJpZM4LPajh>
> > .
>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pascalmolin/hcperiods/pull/7#issuecomment-267699978>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFqZFhf-CdBJmk7PPadBeLxal0FA34Bfks5rIwJAgaJpZM4LPajh>
> .
>

2016-12-19 11:18 UTC, closed without merging